name: Audit

on:
  pull_request:
    branches:
      - master
      - zowe-v?-lts
  schedule:
    - cron: '0 10 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    - name: Check Vulnerabilities
      run: |
        npm install --package-lock-only --ignore-scripts --no-audit --save-prod ./web-help
        npm audit --production --audit-level=moderate
