name: Changelog

on:
  pull_request:
    branches:
      - master

jobs:
  changelog:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') != true }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check Changelog Updated
      uses: awharn/check_changelog_action@v0.0.2
      with:
        header: '## Recent Changes'
        file: 'CHANGELOG.md'
